struct TextConstants {
    static var all = "All"
    static var marsHeader = "MARS.CAMERA"
    static var roverDescription = "Rover: "
    static var cameraDescription = "Camera: "
    static var dateDescription = "Date: "
    static var roverHeader = "Rover"
    static var cameraHeader = "Camera"
    static var dateHeader = "Date"
    static var noData = "No data available for the selected filter"
    static var noHistory = "Browsing history is empty."
    static var saveFilters = "Save Filters"
    static var saveFilterMessage = "The current filters and the date you have chosen can be saved to the filter history."
    static var save = "Save"
    static var cancel = "Cancel"
    static var history = "History"
    static var delete = "Delete"
    static var use = "Use"
    static var menuFilter = "Menu Filter"
    static var filters = "Filters"
}
